"""refactor shipment location

Revision ID: 58a4532d04fc
Revises: 3469ce7f5925
Create Date: 2025-10-04 07:24:51.353324

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58a4532d04fc'
down_revision: Union[str, Sequence[str], None] = '3469ce7f5925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serviceable_location',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.zip_code'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partner.id'], ),
    sa.PrimaryKeyConstraint('partner_id', 'location_id')
    )
    op.drop_column('delivery_partner', 'serviceable_zip_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_table('serviceable_location')
    # ### end Alembic commands ###
